### ISSUE TITLE
convertToJWT method signature changed

### ISSUE THREAD

**Issue by hamedov93** [binarygeotech/passport-booster#3]
Hello George,
Please note that the scope of the method convertToJWT in \Laravel\Passport\Bridge\AccessToken has been changed to **private** in the latest release of league oauth2-server, thus you should implement the whole AccessToken class and not extend passport AccessToken class to be able to override the method.

Actually the method exists in the AccessTokenTrait used by AccessToken class.

If you are using the latest version of passport / league oauth2-server the method will never be called.

Regards.

**Comment by binarygeotech** [comment]
@hamedov93 I'm using this in an active project with `"laravel/passport": "^8.4"` and everything have been working well so far, if there is any use case that I can test with, please let me know. I was just trying to minimize method overrides.

Thanks for your observation.

**Comment by hamedov93** [comment]
May be it doesn't affect authentication / token requests for your package but I am sure it is not called.
So your custom claims are not added to the token.
Just make sure the method is called during token requests .

**Comment by binarygeotech** [comment]
I am very sure it was called. I added the guard to the to the claims and it's present. tested and working perfectly in a project I'm working on.
I'm planning to add the option to add more custom claims though.
Thanks for the feedback.
